[INCLUDE: android_auto/config.ini]
[Display_AndroidAuto]
Meshes = bmw_m135i_13_cockpit_interior_metal2___192_vertices_96_faces
Resolution = 1024, 928
Size = 950, 350
Offset = 33, 283
Scale = 1
RearCameraPosition = 0, 0.646, -2.54
aftermarketComponent=1

[EXTRA_FX]
GLASS_FILTER = Object029
SKIP_GBUFFER = GEO_glasses

[INCLUDE: common/materials_interior.ini]
[Material_DigitalScreen]
Materials = centerscreeen
ScreenScale = 600
ScreenAspectRatio = 0.5
MatrixType = TN

[DATA]
DISABLE_DI_TEXT_NODES = 9


[BOUNCED_HEADLIGHTS]
ACTIVE=1
FADE_AT=200
FADE_SMOOTH=50
FALLOFF=0.4
GRADIENT_OFFSET=0.8
MULT=1, 1, 1, 1
OFFSET=7
---------------------------------------------------------------
[BASIC]
BRAKES_THRESHOLD=0.01
ENGINE_STALLED_RPM_THRESHOLD=1
HAZARD_LIGHTS_ENGINE_LIFE_THRESHOLD=0.001
HEADLIGHTS_ARE_HEADLIGHTS=1
HORN_AS_SIREN=0
IS_LOW_BEAM_AVAILABLE=1
LIGHT_DAMAGE_SPEED_MAX=120
LIGHT_DAMAGE_SPEED_MIN=80
STOP_LODS_ADJUSTMENT=0
TURNING_LIGHTS_REPEAT=1
--------------------------------------------------------------
[LIGHTING]
EMISSIVE_MULT=1
INTERIOR_FAKE_UPPER_SHADOW_HEIGHT=0.3
INTERIOR_FAKE_UPPER_SHADOW_FADE=-0.1
INTERIOR_FAKE_SHADOW_OPACITY=0.9
INTERIOR_FAKE_SHADOW_HEIGHT=-0.1
INTERIOR_FAKE_SHADOW_FAGE=0.5
-------------------------------------------------------------------
[LIGHT_BRAKE_0]
AFFECTS_TRACK=1
BOUND_EMISSIVE_MAX=500
BOUND_EXP=1
COLOR=1, 0.181034, 0, 3
DIFFUSE_CONCENTRATION=0.88
DIRECTION=0, 0, -1
EXTERIOR_ONLY=1
FADE_AT=120
FADE_SMOOTH=30
INTERIOR_ONLY=0
MIRROR=0.655593
MIRROR_DIRECTION=0
POSITION=0, 0.035, -2.1
RANGE=4
RANGE_GRADIENT_OFFSET=0.25
SINGLE_FREQUENCY=0
SPECULAR_MULT=1
SPOT=155
SPOT_EDGE=0.12, 0.12, 0.12
SPOT_EDGE_SHARPNESS=10
SPOT_SHARPNESS=0.4

[LIGHT_HEADLIGHT_0]
AFFECTS_TRACK=1
BOUND_EMISSIVE_MAX=500
BOUND_EXP=1
COLOR=1, 0.9, 1.1, 20
DIFFUSE_CONCENTRATION=0.88
DIRECTION=0, 1.0, 10
EXTERIOR_ONLY=0
FADE_AT=450
FADE_SMOOTH=50
INTERIOR_ONLY=0
LOWBEAM_RANGE_MAX=130
LOWBEAM_RANGE_MULT=5.0
LOWBEAM_RANGE_ONCOMING_MULT=0.8
MIRROR=0.53
MIRROR_DIRECTION=0
POPUP_ENABLED=0
POSITION=0, 0.64, 1.3
RANGE=210
RANGE_GRADIENT_OFFSET=0
SECOND_SPOT=70
SECOND_SPOT_INTENSITY=0.27
SECOND_SPOT_RANGE=10
SECOND_SPOT_SHARPNESS=0.28
SECOND_SPOT_SKIP=0.3
SINGLE_FREQUENCY=0
SPECULAR_MULT=1
SPOT=58
SPOT_EDGE=0.02088, 0.01992, 0.018
SPOT_EDGE_SHARPNESS=50
SPOT_SHARPNESS=0
SPOT_UP=0.0499376, 0.998752, 0
------------------------------------------------------------------


-------------------------------------------------------------------
[INCLUDE: common/materials_carpaint.ini]
CarPaintMaterial =Material #568

[Material_CarPaint]
ClearCoatThickness = 0.1
SpecularColor = 1
SpecularMult = 0.6
FresnelMax = 0.5
FresnelC = 0.1
------------------------------------------------------------------------



;///REAR PLATES CAST///
[LIGHT_LICENSEPLATE]
MESHES=17_0
OFFSET=-0.019, 0.07, 0.001
RANGE=0.35
RANGE_GRADIENT_OFFSET=0.2
SPOT=150s
SPOT_SHARPNESS=0.6
COLOR=10,10,15,1
FALLBACK_EMISSIVE=1,0.7,0.3,0.9
LAYOUT=TWO_ON_TOP
FADE_AT=50
FALLBACK_LOWBEAM_COLOR=1,0.7,0.3,0.9

[INCLUDE: common/selflighting.ini]




;     ///TURN SIGNALS///
[EMISSIVE_TURNSIGNAL_LEFT_0]
lf

NAME=INDICATOR_LF
COLOR=10,4,0, 5
OFF_COLOR=0,0,0, 0
LAG=0.1 
SIMULATE_HEATING=0 
LOCATION=FRONT


[EMISSIVE_TURNSIGNAL_LEFT_1]
lf
NAME=INDICATOR_LS
COLOR=10,4,0, 22 
LAG=0.1 
SIMULATE_HEATING=0 
LOCATION=SIDE

[EMISSIVE_TURNSIGNAL_LEFT_2]
lf
NAME=INDICATOR_LR
COLOR=5,2,0, 22
LAG=0.1 
SIMULATE_HEATING=0 
LOCATION=BACK


[EMISSIVE_TURNSIGNAL_RIGHT_0]
fr
NAME=INDICATOR_RF
COLOR=10,4,0,5
OFF_COLOR=0,0,0, 0
LAG=0.1 
SIMULATE_HEATING=0 
LOCATION=FRONT


[EMISSIVE_TURNSIGNAL_RIGHT_1]
fr
NAME=INDICATOR_RS
COLOR=5,2,0, 22 
LAG=0.1 
SIMULATE_HEATING=0
LOCATION=SIDE

[EMISSIVE_TURNSIGNAL_RIGHT_2]
fr
NAME=INDICATOR_RR
COLOR=5,2,0, 22
LAG=0.1 
SIMULATE_HEATING=0
LOCATION=BACK

[EMISSIVE_REVERSE_0]
NAME=REVERSE
COLOR=10,10,10, 20
LAG=0.1
LOCATION=REAR
SIMULATE_HEATING=0
CAST_LIGHT=1


[EMISSIVE_EXTRA_A_2]
NAME=FOG_FRONT
COLOR=110, 110, 110, 1
LAG=0.1
LOCATION=REAR
SIMULATE_HEATING=0
CAST_LIGHT=1

[EMISSIVE_EXTRA_B_2]
NAME=FOG_REAR
COLOR=110, 0, 0, 3
LAG=0.1
LOCATION=REAR
SIMULATE_HEATING=0
CAST_LIGHT=1







[AUDIO_PITCH]
ENGINE_EXT = 1.03
ENGINE_INT = 1.03
GEAR_EXT = 1.0
GEAR_INT = 1.0
BODYWORK = 1.0
WIND = 1.0
DIRT = 1.0
DOWN_SHIFT = 1.0
HORN = 1.0
GEAR_GRIND = 1.0
BACKFIRE_EXT = 1.0
BACKFIRE_INT = 1.0
TRACTION_CONTROL_EXT = 1.0
TRACTION_CONTROL_INT = 1.0
TRANSMISSION = 1.0
LIMITER = 1.0
TURBO = 1.0
HIT = 1.0
SCRAPE = 1.0
WHEEL = 1.0
SKID_EXT = 1.0
SKID_INT = 1.0

[AUDIO_VOLUME]
ENGINE_EXT = 1.0
ENGINE_INT = 1.0
GEAR_EXT = 0.1
GEAR_INT = 0.1
BODYWORK = 1.0
WIND = 1.0
DIRT = 1.0
DOWN_SHIFT = 0.1
HORN = 1.0
GEAR_GRIND = 1.0
BACKFIRE_EXT = 1.0
BACKFIRE_INT = 1.0
TRACTION_CONTROL_EXT = 1.0
TRACTION_CONTROL_INT = 1.0
TRANSMISSION = 0.1
LIMITER = 1.0
TURBO = 0.3


[ODOMETER_MAIN]
DIGITAL_ITEM=4
DIGITAL_ITEM_NUMBER_FORMAT=06.0
UPPER_BOUND=999999

[ODOMETER_TRIP]
DIGITAL_ITEM=5
DIGITAL_ITEM_NUMBER_FORMAT=06.1
UPPER_BOUND=9999



                                        ///realistic_glass

[INCLUDE: common/materials_glass.ini]
ExteriorGlassHeadlightsMaterials =window

[Material_PhotoelasticGlass]
Meshes =GLASS_OUT
PhotoelasticityBaseScale = 0      ; this parameter alters scale in general
PhotoelasticityNoiseScale = 0.00  ; deeply affects randomization process, careful with it
PhotoelasticitySpotsScale = 0.0   ; spots for limiting effect to some areas
PhotoelasticitySpotsOffset = 0.0  ; offset for spots, to try and fit effect nice on existing meshes
PhotoelasticityStripesScale = 0  ; how many stripes are there
ProfileFix = 0.01
FilmIOR=3.0
ThicknessMult=2.0
Desaturate=1
EXTRA_MASK_PASS=1

---------------------------------------------------------------------------------------------------------------
					///FRONT_HEADLIGHTS_GLASS
[INCLUDE: common/materials_glass.ini]
ExteriorGlassFilmedMaterials=
ExteriorGlassTintedMaterials=rad_smoothglass_#FFFFFFFF
ExteriorGlassHeadlightsMaterials=rad_smoothglass_#FFFFFFFF

[Material_PhotoelasticGlass]
Meshes =bmw_m135i_13_lod0_glassLHL_glass___347_vertices_762_faces
PhotoelasticityBaseScale=4        ; this parameter alters scale in general
PhotoelasticityNoiseScale=0.4    ; deeply affects randomization process, careful with it
PhotoelasticitySpotsScale=0.009     ; spots for limiting effect to some areas
PhotoelasticitySpotsOffset=0.3   ; offset for spots, to try and fit effect nice on existing meshes
PhotoelasticityStripesScale=1.7   ; how many stripes are there
ProfileFix=0.01
FilmIOR=3.5
ThicknessMult=2.0
Desaturate=1
EXTRA_MASK_PASS=1

[SHAKING_EXHAUST_...]
MESHES =bmw_m135i_13_lod0_exhaustLa_frame___146_vertices_230_faces,bmw_m135i_13_lod0_exhaustLa_chrome_3___1284_vertices_2060_faces
POINT_0_SCALE = 0.45
POINT_0 = -0.14, 0.12, -0.054
POINT_0_RADIUS = 1.0
POINT_0_EXP = 0.001

================================================
[EMISSIVE_HIGHBEAM_...]
NAME =
COLOR =191,151,151, 2
ACT_AS_HEADLIGHTS=1
LAG = 0.1
SIMULATE_HEATING = 0.01
LOCATION = FRONT

[EMISSIVE_HIGHBEAM_...]
NAME =
COLOR =12,12,12, 1
ACT_AS_HEADLIGHTS=0
LAG = 0.1
SIMULATE_HEATING = 0.01
LOCATION = FRONT

----DASHBOARD----
[EMISSIVE_LIGHT_...]
NAME=DASH_NIGTH
COLOR=8,2,1,1.1
LAG=0.1
LOCATION=FRONT
SIMULATE_HEATING=1
CAST_LIGHT=1
ACT_AS_HEADLIGHTS=0

--------DIALS---------
[EMISSIVE_LIGHT_...]
NAME=Object021,Object022,Object023
COLOR=8,2,1.3,0.9
LAG=0.1
LOCATION=FRONT
SIMULATE_HEATING=1
CAST_LIGHT=1
ACT_AS_HEADLIGHTS=0


[EMISSIVE_LIGHT_...]
NAME=bmw_m135i_13_cockpit_interior_plastic___18182_vertices_19821_faces001,bmw_m135i_13_cockpit_steering_wheel_z_gauge_emissive_alpha___60_vertices_52_faces
COLOR=5,0.5,0,1.5
LAG=0.1
LOCATION=FRONT
SIMULATE_HEATING=1
CAST_LIGHT=1
ACT_AS_HEADLIGHTS=0

[EMISSIVE_LIGHT_...]
NAME=bmw_m135i_13_cockpit_interior_metal2___192_vertices_96_faces
COLOR=1,1,1,1
OFF_COLOR=1,1,1,1.1
LAG=0.2
LOCATION=BACK
SIMULATE_HEATING=1
CAST_LIGHT=1
ACT_AS_HEADLIGHTS=1

[EMISSIVE_LIGHT_...]
NAME=LIGTH_ON_REAR
COLOR=114,0,0,1
LAG=0.2
LOCATION=REAR
SIMULATE_HEATING=1
CAST_LIGHT=1
ACT_AS_HEADLIGHTS=1


[EMISSIVE_LIGHT_...]
NAME=DAY_RUN_1,DAY_RUN_2
COLOR=14,8,2,1.1
LAG=0.1
LOCATION=FRONT
SIMULATE_HEATING=1
CAST_LIGHT=1
ACT_AS_HEADLIGHTS=1

[EMISSIVE_LIGHT_...]
NAME=
COLOR=14,14,18,0.6
OFF_COLOR=0,0,0, 0
LAG=0.1
LOCATION=FRONT
SIMULATE_HEATING=1
CAST_LIGHT=1
ACT_AS_HEADLIGHTS=1

[EMISSIVE_LIGHT_...]
NAME =bmw_m135i_13_cockpit_interior_metal2___192_vertices_96_faces001
COLOR =11,11,13, 0.03

ACT_AS_HEADLIGHTS=1
LAG = 0.1
SIMULATE_HEATING = 0.01
LOCATION = FRONT

[EMISSIVE_LIGHT_...]
NAME=bmw_m135i_13_cockpit_interior_digital_gauge___112_vertices_117_faces
COLOR=2,2,2,0.7
LAG=0.1
LOCATION=FRONT
SIMULATE_HEATING=1
CAST_LIGHT=1
ACT_AS_HEADLIGHTS=0




;=========================DASH=======================






[LIGHT_TURNSIGNAL_LEFT_3]
BOUND_EMISSIVE_MAX=0
BOUND_EXP=1

[LIGHT_TURNSIGNAL_RIGHT_3]
BOUND_EMISSIVE_MAX=0
BOUND_EXP=1

[SHADER_REPLACEMENT_...]
MESHES=glassR_window_int
SHADER=ksWindscreen

[BASIC]
DIESEL_ENGINE = 0		; or 1

[PARTICLES_FX_EXHAUST_0]
POSITION=0.4226721,0.1347981,-2.225424
DIRECTION=-0.01848446,-0.01251572,-0.9997509
COLOR = 0.75,0.8,1  			; RGB blend - 0,0,0 is black, 1,1,1 is white
LIFE = 1, 2 				; how long particles last in the air before disappearing
SPEED = 0.5, 1 				; how fast smoke particles fly from the exhaust
SPREAD = 0.25				; initial spread of particles
STARTING_SIZE = 0.04			; initial size of particles
SPAWN_OFFSET = 0.02			; initial spawn point offset (length-wise)
INTENSITY = 0.25, 0.3			; smoke intensity
TEMPERATURE_LAG = 1 			; engine heating up (1 to disable)
SPEED_THRESHOLD = 15, 100 		; speed at which the smoke disappears

[PARTICLES_FX_EXHAUST_1]
POSITION=-0.4174524,0.13755,-2.19354
DIRECTION=-0.01869227,-0.002979205,-0.9998209		; self explanatory
COLOR = 0.75,0.8,1  			; RGB blend - 0,0,0 is black, 1,1,1 is white
LIFE = 1, 2 				; how long particles last in the air before disappearing
SPEED = 0.5, 1 				; how fast smoke particles fly from the exhaust
SPREAD = 0.25				; initial spread of particles
STARTING_SIZE = 0.04			; initial size of particless
SPAWN_OFFSET = 0.02			; initial spawn point offset (length-wise)
INTENSITY = 0.25, 0.3			; smoke intensity
TEMPERATURE_LAG = 1 			; engine heating up (1 to disable)
SPEED_THRESHOLD = 15, 100 		; speed at which the smoke disappears




----------------------------------------------------
--               EXHAUST               --
----------------------------------------------------

[INCLUDE: common/gt3_exhaust_glow.ini]
[EMISSIVE_WATER_TEMP_0_EXHAUST_GLOW]
MESHES =
1COLOR = 125, 10, 0, 3
USE_SMOOTH_TRANSITION = 1
INPUT_MIN = 82
INPUT_MAX = 93
INPUT_LUT = (| 84 = 0 | 95 = 1 |)
AFFECTS_TRACK = 1
SPECULAR_MULT = 3

[ANIMATION_1]
FILE=trunk_anim.ksanim
TIME= 2
BIND_TO_EXTRA_A=1

[ANIMATION_2]
FILE=hood_anim.ksanim
TIME= 2
BIND_TO_EXTRA_B=1




[ANALOG_INDICATOR_...]
INPUT=OIL_PRESSURE
NAME=ARROW_OIL
ZERO=-1.8
STEP=-11.1

[ANALOG_INDICATOR_...]
INPUT=WATER_TEMP
NAME=ARROW_TEMP
ZERO=-25
STEP=-1.02

[ANALOG_INDICATOR_...]
INPUT=OIL_PRESSURE
NAME=ARROW_BAT
ZERO=1.9
STEP=3



[EXHAUST_FLAMES]
ANTILAG=1 ; turbo antilag, i havent tested this yet
ANTILAG_DELAY=0.00 ; how long after antilag trigger do flames start, in seconds
ANTILAG_INTENSITY= 0.05 ; flame size
ANTILAG_INTERVAL_MAX=0.3
ANTILAG_INTERVAL_MIN=0.08
ANTILAG_TURBO_THRESHOLD=0.1
DAMAGE=0 ; engine damage? idk
DAMAGE_DURATION=0.05
DAMAGE_INTENSITY=1
DAMAGE_PROBABILITY=1
DISCHARGE=1.0 ; lifting off the throttle
DISCHARGE_CHARGE_TIME=0.1 ; how long you have to press the throttle to "charge" the flames
DISCHARGE_DELAY=0.0 ; delay after throttle lift
DISCHARGE_DURATION=0.7 ; length of flame shooting, in seconds
DISCHARGE_PROBABILITY=0.8; chance of flame shoot on lift, 1 is guaranteed, 0 is never
DISCHARGE_INTENSITY=0.01; flame size
DISCHARGE_RPM_THRESHOLD_MAX=7500 ; self explanatory
DISCHARGE_RPM_THRESHOLD_MIN=4500 ; self explanatory
DISCHARGE_WATER_TEMPERATURE_THRESHOLD=70
FLAT_SHIFT=1 ; on upshift
FLAT_SHIFT_COOLDOWN=0.03 ; after upshift
FLAT_SHIFT_DURATION=0.002 ; length of flame shooting, in seconds
FLAT_SHIFT_GAS_THRESHOLD=40 ; how much gas needs to be pressed on upshift for flame, 100 is wide open
FLAT_SHIFT_INTENSITY=1.0 ; flame size
FLAT_SHIFT_PROBABILITY=1.0 ; chance of flame shoot on upshift
FLAT_SHIFT_RPM_THRESHOLD=4000
LIMITER=0.0 ; on hitting the limiter
LIMITER_DELAY=0.0 ; delay, in seconds
LIMITER_INTENSITY=0.0001 ; flame size
LIMITER_RPM_THRESHOLD=6500 ; limiter flames will not shoot below this rpm


[ANIMATED_...]
NODE=belt_spin
SPIN_AXIS=1,0,0
WINDMILL_DIR=-1,0,0
SPIN_AXIS=1,0,0
WINDMILL_DIR=-1,0,0
SPEED_MULT=0.05
LAG_UP=0.9

[AUDIO_PROPERTIES]
ENGINE_EXT_BOOST=1
ENGINE_INT_BOOST=1
TURBO_THROTTLE=1

[INSTRUMENTS]
SPEED_LAG=0.7
SPEED_LIMIT=120

[BOUNCED_HEADLIGHTS]
ACTIVE=1
FADE_AT=200
FADE_SMOOTH=50
FALLOFF=0.7
GRADIENT_OFFSET=0.8
MULT=1, 1, 1, 1
OFFSET=7




[REFRACTING_HEADLIGHT_0]
SURFACE =LOW_BEAM_GLASS
INSIDE =LOW_BEAM

[REFRACTING_HEADLIGHT_1]
SURFACE =INDICATOR_RF
INSIDE =INDICATOR_RF_1,INDICATOR_RF_2,INDICATOR_RF_3

[REFRACTING_HEADLIGHT_2]
SURFACE =INDICATOR_LF
INSIDE =INDICATOR_LF_1,INDICATOR_LF_2,INDICATOR_LF_3


[REFRACTING_HEADLIGHT_3]
SURFACE =BRAKE_MID
INSIDE =BRAKE_MID_IN



[REFRACTING_HEADLIGHT_4]
SURFACE =INDICATOR_LR
INSIDE =INDICATOR_LR_IN

[REFRACTING_HEADLIGHT_5]
SURFACE =LIGTH_ON_REAR
INSIDE =LIGTH_ON_REAR_IN


[REFRACTING_HEADLIGHT_6]
SURFACE =FOG_REAR
INSIDE =Object030

[REFRACTING_HEADLIGHT_7]
SURFACE =INDICATOR_RR
INSIDE =INDICATOR_RR_IN






[REFRACTING_HEADLIGHT_8]
SURFACE =REVERSE
INSIDE =REVERSE_IN




[REFRACTING_HEADLIGHT_9]
SURFACE =
INSIDE =

[REFRACTING_HEADLIGHT_10]
SURFACE =
INSIDE =








[REFRACTING_HEADLIGHT_11]
SURFACE = 
INSIDE =




[REFRACTING_HEADLIGHT_12]
SURFACE = 
INSIDE =


[REFRACTING_HEADLIGHT_13]
SURFACE = 
INSIDE =

[REFRACTING_HEADLIGHT_14]
SURFACE = 
INSIDE =



[LIGHTING]
INTERIOR_FAKE_UPPER_SHADOW_HEIGHT=0.0
INTERIOR_FAKE_UPPER_SHADOW_FADE=-0.5
INTERIOR_FAKE_SHADOW_OPACITY=0.9
INTERIOR_FAKE_SHADOW_HEIGHT=0.4
INTERIOR_FAKE_SHADOW_FAGE=0.5


[INCLUDE: common/custom_emissive.ini]

[CustomEmissiveMulti]
Meshes =DASH_WARNING
UseEmissive0AsFallback = 2
Resolution = 1024,1024

@ = MultiItem, Role = HIGHBEAM, Start = "469, 431", Size = "47, 32"
@ = MultiItem, Role = LIGHT, Start = "111,652", Size = "39, 21", Color = "0, 30, 0",
@ = MultiItem, Role = HANDBRAKE, Start = "466, 586", Size = "46, 34", Color = "15, 0.3, 0, 2"


@ = MultiItem, Role = STALLED, Start = "69, 647", Size = "39,28 " , Lag=0.2, Color = "7,3,0, 2"
@ = MultiItem, Role = STALLED, Start = "251, 715", Size = "62, 37", Color = "15, 0.3, 0, 2"
@ = MultiItem, Role = STALLED, Start = "200, 716", Size = "40, 33", Color = "7,3,0, 2"


@ = MultiItem, Role = TYRE_PRESSURE, Start = "521, 589", Size = "41, 33", Color = "30, 15, 0", InputThreshold = 41, InputSelector = MAX , InputSelectorPivot=5 , Lag=0.2 
@ = MultiItem, Role = ABS, InputInverse,Start = "322, 717", Size = "38, 30" , Color = "7,3,0, 5"
@ = MultiItem, Role = TRACTIONCONTROL, InputInverse, Start = "474, 548", Size = "33, 32" , Lag=0.2, Color = "7,3,0, 2"
@ = MultiItem, Role = TC_INACTION , Start = "524, 543", Size = "31, 40", Color = "7,3,0, 2"
@ = MultiItem, Role = TURNSIGNAL_LEFT, Start = "406, 323", Size = "50, 50" , Color = "1,5,1, 4 " 
@ = MultiItem, Role = TURNSIGNAL_RIGHT, Start = "577, 322", Size = "51, 48" , Color = "1,5,1, 4 " 
@ = MultiItem, Role = EXTRA_B, Start = "156, 681", Size = "36, 28", Color = "13, 5, 0",
@ = MultiItem, Role = EXTRA_A, Start = "114, 682", Size = "34, 27", Color = "1, 9, 1",
 



[WIPERS_TRACE_...]
SURFACE =GLASS_OUT,GLASS_IN
WIPERS =Object028,Object027,bmw_m135i_13_lod0_trunk_plastic2___845_vertices_1763_faces

[WIPERS]
WIND_THRESHOLDS_KMH = 200, 290 ; speed for wipers to start vibrating and for maximum vibration
WIND_AMPLITUDE_MULT = 1 ; multiplier for amplitude
WIND_FREQUENCY_MULT = 1 ; multiplier for frequency
WIND_OFFSET = 0.03 ; base animation2

[BRAKEDISC_FX]
ACTIVE = 0   

